export const ActionPremiumTypes= {
    SET_PREMIUM : "SET_PRODUCTS",
    SELECTED_PREMIUM:"SELECTED-PRODUCTS",
    REMOVE_SELECTED_PREMIUM:"REMOVE_SELECTED_PRODUCTS",
    EDIT_PREMIUM:"EDIT_PRODUCTS"
}